// // ACTIONS FOR CART
// export const ADD_TO_CART = 'ADD_TO_CART';
// export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
// export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';

// // ACTIONS LOGIN & OUT
// export const LOGIN = 'LOGIN';
// export const LOGOUT = 'LOGOUT';

// // ACTIONS FOR PRESCRIPTION
// export const UPLOAD_PRESCRIPTION = 'UPLOAD_PRESCRIPTION';

// // ACTIONS FOR USER LOCATION
// export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
